app_id: 6L903538-42B1-4596-G479-BJ779F21A65D
publisher: Moneyfly
publisher_url: https://github.com/moneyfly004/windows
display_name: Moneyfly
executable_name: Moneyfly.exe
output_base_file_name: Moneyfly.exe
create_desktop_icon: true
install_dir_name: "{autopf64}\\Moneyfly"
setup_icon_file: ..\..\windows\runner\resources\app_icon.ico
locales:
  - ar
  - en
  - fa
  - ru
  - pt
  - tr
script_template: inno_setup.sas
